point_cloud_topic: /zed2/point_cloud/cloud_registered
map_frame_id: "map"
robot_base_frame_id: "base_link"
robot_pose_with_covariance_topic: "/odometry/filtered/pose"
robot_pose_cache_size: 200
track_point_frame_id: "base_link"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
min_update_rate: 1.0
fused_map_publishing_rate: 0.5
