obstacle_range: 2.0
raytrace_range: 3.0
footprint: [[-0.25, -0.23], [-0.25, 0.23], [0.25, 0.23], [0.25, -0.23]]
#robot_radius: ir_of_robot
inflation_radius: 0.2

recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]

conservative_clear: 
    reset_distance: 10.00
aggressive_clear:
    reset_distance: 20.00
