global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  transform_tolerance: 0.5
  rolling_window: true
  width: 30.0
  height: 30.0

  observation_sources:  point_cloud_sensor

  point_cloud_sensor: {sensor_frame: base_link, 
                      data_type: "PointCloud2",  
                      topic: openni_points, 
                      marking: true, 
                      clearing: true,
                      min_obstacle_height: -99999.0,
                      max_obstacle_height: 99999.0}
